Instantly scale up capacity when using Tune(size int) to enlarge the capacity
panjf2000/ants pull request #210
Opened 2022-01-29 08:01 UTC by codingfanlt

…capacity

---
name: Pull request
about: Propose changes to the code
title: 'Instantly scale up capacity when using Tune(size int) to enlarge the capacity'
labels: 'enhancement'
assignees: ''
---

## 1. Are you opening this pull request for bug-fixs, optimizations or new feature?

When using Tune(size int) to enlarge the capacity, create a worker immediately to perform blocking tasks.

## 2. Please describe how these code changes achieve your intention.

## 3. Please link to the relevant issues (if any).

close #205 

## 4. Which documentation changes (if any) need to be made/updated because of this PR?

## 4. Checklist

- [x] I have squashed all insignificant commits.
- [x] I have commented my code for explaining package types, values, functions, and non-obvious lines.
- [ ] I have written unit tests and verified that all tests passes (if needed).
- [ ] I have documented feature info on the README (only when this PR is adding a new feature).
- [x] (optional) I am willing to help maintain this change if there are issues with it later.

2022-01-31 02:42 UTC, panjf2000 requested changes

2022-01-31 02:42 UTC, panjf2000 commented on pool.go
> +		p.cond.Broadcast()
麻烦补充一点测试。

2022-02-07 11:44 UTC, codingfanlt commented on pool.go
> +		p.cond.Broadcast()
> 麻烦补充一点测试。

已添加相关单元测试

2022-02-08 05:56 UTC, panjf2000 commented on pool.go
> +		p.cond.Broadcast()
这部分修改也需要改 pool_func.go

2022-02-09 06:16 UTC, codingfanlt commented on pool.go
> +		p.cond.Broadcast()
已修改

2022-02-09 15:06 UTC, panjf2000 requested changes

2022-02-09 15:06 UTC, panjf2000 commented on ants_test.go
> +
这里加一下 `close(c)`，然后 `p.Release()`，下面同理。

2022-02-14 11:13 UTC, codingfanlt commented on ants_test.go
> +
已修改，但其实 `p.Release()` 之后仍然有 task 在跑。如果想要优雅关闭需要添加 `pool.Wait()` 方法在程序退出前等待 task 全部运行完毕。

2022-02-14 13:51 UTC, panjf2000 approved these changes
LGTM

2022-02-14 13:51 UTC, merged

2022-02-14 13:51 UTC, panjf2000 commented
Thanks~