Add a new method -- ReleaseWaitAllWorkersExit() for waiting all worke…
panjf2000/ants pull request #245
Opened 2022-08-05 08:03 UTC by cuishuang

fix issue https://github.com/panjf2000/ants/issues/244

2022-08-08 13:55 UTC, panjf2000 commented on pool.go
> +	for {
这里有一个风险，如果某一个 worker 里的任务阻塞了，则这里就永远无法退出了。

2022-08-08 13:56 UTC, panjf2000 commented on pool.go
> +	for {
另外，其实你这里的代码和 `ReleaseTimeout(timeout)` 基本是一样的，我更倾向于直接修改 `ReleaseTimeout(timeout)`，当 timeout < 0 的时候，就一直等到所有 workers 退出才结束。

2022-08-08 13:57 UTC, panjf2000 requested changes
PTAL

2023-11-24 17:48 UTC, skydiver1980 approved these changes

2024-10-04 00:06 UTC, closed without merging