Unblock goPurge and goTicktock in defaultAntsPool
panjf2000/ants pull request #281
Opened 2023-06-28 02:41 UTC by ELchem

---
name: Unblock goPurge and goTicktock in defaultAntsPool
about: ants.Release() calls defaultAntsPool.Release() which leaves goPurge and goTicktock still running in the background. ants.Release() should close the context for goPurge and goTicktock. This can be accomplished by calling defaultAntsPool.ReleaseTimeout(<large number>). 
title: 'Unblock goPurge and goTicktock in defaultAntsPool'
labels: ''
assignees: ''
---

## 1. Are you opening this pull request for bug-fixs, optimizations or new feature?
Bug-fix.

## 2. Please describe how these code changes achieve your intention.

goPurge and goTicktock are left on the stack because there is no way to close those methods started by the defaultAntsPool. This PR should add a fix for that.   

## 3. Please link to the relevant issues (if any).

https://github.com/panjf2000/ants/issues/244

## 4. Which documentation changes (if any) need to be made/updated because of this PR?

## 4. Checklist

- [x] I have squashed all insignificant commits.
- [x] I have commented my code for explaining package types, values, functions, and non-obvious lines.
- [x] I have written unit tests and verified that all tests passes (if needed).
- [x] I have documented feature info on the README (only when this PR is adding a new feature).
- [x] (optional) I am willing to help maintain this change if there are issues with it later.

2023-06-28 13:26 UTC, panjf2000 commented
We should add a new API like `ReleaseTimeout` instead of modifying an existing one.

2023-06-29 01:16 UTC, ELchem commented
I added a function called ReleaseTimeout() to ants.go. Is that what you had in mind?

2023-06-29 01:19 UTC, panjf2000 requested changes
Please add some new test cases for this new API.

2023-06-29 05:40 UTC, panjf2000 requested changes

2023-06-29 05:40 UTC, panjf2000 commented on ants_test.go
> +	for i := 0; i < 5; i++ {
Since the default pool has been released by the previous tests, you should call `Reboot()` before starting your new tests.

2023-06-30 11:55 UTC, panjf2000 approved these changes
LGTM, thanks~

2023-06-30 11:56 UTC, merged

2023-06-30 12:04 UTC, panjf2000 commented
I did not check carefully before, we've changed the default branch from `master` to `dev`, you should open a pull request aginst `dev`, not `master`, reverting it.

2023-06-30 14:10 UTC, panjf2000 commented
Please open a new pull request to branch `dev` when you have time, sorry about that.